import type {
  CatalogImportStats,
  CatalogImportTemplate,
  CatalogRows,
  CellValue,
  ParsedCatalog,
  ParsedCategory,
  ParsedProduct,
  ParsedVendor,
  RowReader,
} from "./types";

type ColumnIndexes = Record<string, number>;

const requiredColumnKeys = ["itemNumber", "name"] as const;

export function parseCatalog(
  rows: CatalogRows,
  template: CatalogImportTemplate,
): ParsedCatalog {
  const headerRowIndex = template.headerRowIndex ?? 0;
  const headerRow = rows[headerRowIndex];

  if (!headerRow) {
    throw new Error(`Missing header row at index ${headerRowIndex}`);
  }

  const columnIndexes = resolveColumnIndexes(headerRow, template);
  const dataRows = rows.slice(headerRowIndex + 1);
  const categories: ParsedCategory[] = [];
  const vendors: ParsedVendor[] = [];
  const vendorIdsByName = new Map<string, number>();
  const products: ParsedProduct[] = [];
  const seenProducts = new Set<number>();
  const locations = [...(template.locations ?? [])];
  let currentCategory: ParsedCategory | null = null;
  let skippedRows = 0;
  let duplicateProducts = 0;

  for (const rawRow of dataRows) {
    const row = createRowReader(rawRow, columnIndexes);
    const itemNumberValue = row.get("itemNumber");
    const itemNumberText = cellText(itemNumberValue);
    const name = row.text("name");

    if (itemNumberText == null || name == null) {
      skippedRows += 1;
      continue;
    }

    if (template.isCategoryRow(row)) {
      const categoryId = row.integer("itemNumber");

      if (categoryId == null) {
        throw new Error(`Category row has invalid item number: ${itemNumberText}`);
      }

      currentCategory = {
        id: categoryId,
        name,
        sort_order: row.number("categorySortOrder") ?? 0,
      };
      categories.push(currentCategory);
      continue;
    }

    const itemNumber = row.integer("itemNumber");

    if (itemNumber == null) {
      skippedRows += 1;
      continue;
    }

    const vendorName = optionalCodeText(row, "vendor");

    if (vendorName && !vendorIdsByName.has(vendorName)) {
      const vendor = {
        id: vendorIdsByName.size + 1,
        name: vendorName,
      };
      vendorIdsByName.set(vendor.name, vendor.id);
      vendors.push(vendor);
    }

    if (seenProducts.has(itemNumber)) {
      duplicateProducts += 1;
      continue;
    }

    seenProducts.add(itemNumber);
    const attributes = parseAttributes(name, template.attributeRegexes);
    products.push({
      item_number: itemNumber,
      name,
      category_id: currentCategory?.id ?? null,
      vendor_id: vendorName ? (vendorIdsByName.get(vendorName) ?? null) : null,
      brand_number: optionalCodeText(row, "brandNumber"),
      pack: optionalCodeText(row, "pack"),
      sold_as: optionalCodeText(row, "soldAs"),
      retail_price: row.number("retailPrice"),
      attributes,
      shot_count: numberAttribute(attributes, "shot_count"),
      gram_weight: numberAttribute(attributes, "gram_weight"),
      wholesale_excluded: template.wholesaleExcluded?.(row) ?? false,
      is_active: true,
    });
  }

  return {
    templateName: template.name,
    categories,
    vendors,
    products,
    locations,
    parseStats: {
      sourceRows: dataRows.length,
      skippedRows,
      duplicateProducts,
    },
  };
}

export function catalogStats(parsed: ParsedCatalog): CatalogImportStats {
  return {
    ...parsed.parseStats,
    categories: parsed.categories.length,
    vendors: parsed.vendors.length,
    products: parsed.products.length,
    locations: parsed.locations.length,
    productsWithShotCount: parsed.products.filter((product) => product.shot_count != null).length,
    productsWithGramWeight: parsed.products.filter((product) => product.gram_weight != null).length,
    wholesaleExcluded: parsed.products.filter((product) => product.wholesale_excluded).length,
  };
}

export function toSql(parsed: ParsedCatalog): string {
  const lines = [
    "-- Generated by @waltersignal/bananaforce-catalog-import; do not edit by hand.",
    `-- Template: ${parsed.templateName}.`,
    "",
  ];

  appendInsert(
    lines,
    "locations",
    ["slug", "name", "address", "city", "state", "zip", "phone", "hours", "is_public", "sort_order"],
    parsed.locations.map((location) => [
      sqlString(location.slug),
      sqlString(location.name),
      sqlString(location.address),
      sqlString(location.city),
      sqlString(location.state),
      sqlString(location.zip),
      sqlString(location.phone),
      sqlString(location.hours),
      sqlBoolean(location.is_public),
      sqlNumber(location.sort_order),
    ]),
    "slug",
  );

  appendInsert(
    lines,
    "categories",
    ["id", "name", "sort_order"],
    parsed.categories.map((category) => [
      sqlInteger(category.id),
      sqlString(category.name),
      sqlNumber(category.sort_order),
    ]),
    "id",
  );

  // Vendors use a serial id; emit names only and let the sequence assign ids.
  // Products reference vendors by their natural key (name) via a subselect, so
  // FKs stay correct even if the table already has rows or the sheet's vendor
  // order changes between runs (and the serial sequence is never left behind).
  appendInsert(
    lines,
    "vendors",
    ["name"],
    parsed.vendors.map((vendor) => [sqlString(vendor.name)]),
    "name",
  );

  const vendorNameById = new Map(parsed.vendors.map((vendor) => [vendor.id, vendor.name]));

  appendInsert(
    lines,
    "products",
    [
      "item_number",
      "name",
      "category_id",
      "vendor_id",
      "brand_number",
      "pack",
      "sold_as",
      "retail_price",
      "attributes",
      "shot_count",
      "gram_weight",
      "wholesale_excluded",
      "is_active",
    ],
    parsed.products.map((product) => productSqlValues(product, vendorNameById)),
    "item_number",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

export function cellText(value: CellValue): string | null {
  const rawText = cellTextRaw(value);
  if (rawText == null) return null;

  const trimmed = rawText.trim();
  return trimmed === "" ? null : trimmed;
}

export function cellNumber(value: CellValue): number | null {
  if (value == null) return null;

  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }

  if (typeof value === "object") {
    const result = cellObjectResult(value);
    if (result !== undefined) return cellNumber(result);
  }

  const text = cellText(value);
  if (text == null) return null;

  const parsed = Number(text);
  return Number.isFinite(parsed) ? parsed : null;
}

export function cellInteger(value: CellValue): number | null {
  const parsed = cellNumber(value);
  return parsed == null ? null : Math.trunc(parsed);
}

function resolveColumnIndexes(
  headerRow: readonly CellValue[],
  template: CatalogImportTemplate,
): ColumnIndexes {
  const headerIndexes = new Map<string, number>();

  headerRow.forEach((header, index) => {
    const normalized = normalizeHeader(header);
    if (normalized && !headerIndexes.has(normalized)) {
      headerIndexes.set(normalized, index);
    }
  });

  const indexes: ColumnIndexes = {};
  const missing: string[] = [];

  for (const requiredKey of requiredColumnKeys) {
    if (!template.columns[requiredKey]) {
      missing.push(`${requiredKey} (no mapped header name)`);
    }
  }

  for (const [columnKey, headerName] of Object.entries(template.columns)) {
    if (!headerName) continue;

    const headerIndex = headerIndexes.get(normalizeHeader(headerName));

    if (headerIndex == null) {
      missing.push(`${columnKey}: ${headerName}`);
      continue;
    }

    indexes[columnKey] = headerIndex;
  }

  if (missing.length > 0) {
    const availableHeaders = headerRow
      .map((header) => cellText(header))
      .filter((header): header is string => header != null)
      .join(", ");
    throw new Error(
      `Missing mapped catalog import column(s): ${missing.join("; ")}. Available headers: ${availableHeaders}`,
    );
  }

  return indexes;
}

function createRowReader(raw: readonly CellValue[], columnIndexes: ColumnIndexes): RowReader {
  return {
    raw,
    get(columnKey) {
      const index = columnIndexes[columnKey];
      return index == null ? null : (raw[index] ?? null);
    },
    text(columnKey) {
      return cellText(this.get(columnKey));
    },
    number(columnKey) {
      return cellNumber(this.get(columnKey));
    },
    integer(columnKey) {
      return cellInteger(this.get(columnKey));
    },
  };
}

// Optional text/code columns (vendor, brand #, pack, sold as) use a numeric 0
// (or boolean false) as the sheet's empty sentinel. Mirrors the reference
// parser's `if cell` Python-falsiness guard: numeric 0 / false -> no value,
// while a literal "0" string is preserved as text. Formula cells are unwrapped
// to their cached result first, so a formula that evaluates to 0 is also empty.
function optionalCodeText(row: RowReader, columnKey: string): string | null {
  const raw = row.get(columnKey);
  const resolved =
    raw !== null && typeof raw === "object" ? (cellObjectResult(raw) ?? raw) : raw;
  if (resolved === 0 || resolved === false) return null;
  return cellText(raw);
}

function parseAttribute(name: string, regex: RegExp | undefined): number | null {
  if (!regex) return null;

  regex.lastIndex = 0;
  const match = regex.exec(name);
  return match?.[1] ? cellInteger(match[1]) : null;
}

function parseAttributes(
  name: string,
  regexes: CatalogImportTemplate["attributeRegexes"],
): Record<string, number> {
  const attributes: Record<string, number> = {};
  if (!regexes) return attributes;

  for (const [rawKey, regex] of Object.entries(regexes)) {
    const value = parseAttribute(name, regex);
    if (value == null) continue;
    attributes[normalizeAttributeKey(rawKey)] = value;
  }

  return attributes;
}

function normalizeAttributeKey(key: string): string {
  if (key === "shotCount") return "shot_count";
  if (key === "gramWeight") return "gram_weight";
  return key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function numberAttribute(attributes: Record<string, number>, key: string): number | null {
  const value = attributes[key];
  return Number.isFinite(value) ? value : null;
}

function appendInsert(
  lines: string[],
  table: string,
  columns: readonly string[],
  rows: readonly (readonly string[])[],
  conflictKey: string,
) {
  if (rows.length === 0) return;

  lines.push(`insert into ${table} (${columns.join(", ")}) values`);
  lines.push(rows.map((row) => `  (${row.join(", ")})`).join(",\n"));
  lines.push(`on conflict (${conflictKey}) do nothing;`);
  lines.push("");
}

function productSqlValues(product: ParsedProduct, vendorNameById: Map<number, string>) {
  return [
    sqlInteger(product.item_number),
    sqlString(product.name),
    sqlInteger(product.category_id),
    sqlVendorRef(product.vendor_id, vendorNameById),
    sqlString(product.brand_number),
    sqlString(product.pack),
    sqlString(product.sold_as),
    sqlMoney(product.retail_price),
    sqlJson(product.attributes),
    sqlInteger(product.shot_count),
    sqlInteger(product.gram_weight),
    sqlBoolean(product.wholesale_excluded),
    sqlBoolean(product.is_active),
  ];
}

// Resolve a product's vendor by name at apply time. vendors.id is serial, so a
// run-local integer would be wrong against an existing table; the subselect
// reads the actual id. Returns null when the product has no vendor.
function sqlVendorRef(vendorId: number | null, vendorNameById: Map<number, string>): string {
  if (vendorId == null) return "null";
  const name = vendorNameById.get(vendorId);
  return name == null ? "null" : `(select id from vendors where name = ${sqlString(name)})`;
}

function sqlString(value: string | null | undefined): string {
  const text = cellText(value);
  return text == null ? "null" : `'${text.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  return value == null || !Number.isFinite(value) ? "null" : String(value);
}

// retail_price is numeric(10,2): round to cents and drop binary float noise
// (e.g. 0.1 + 0.2 -> "0.30" instead of "0.30000000000000004").
function sqlMoney(value: number | null | undefined): string {
  return value == null || !Number.isFinite(value) ? "null" : value.toFixed(2);
}

function sqlInteger(value: number | null | undefined): string {
  return value == null || !Number.isFinite(value) ? "null" : String(Math.trunc(value));
}

function sqlJson(value: Record<string, unknown>): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function sqlBoolean(value: boolean): string {
  return value ? "true" : "false";
}

function normalizeHeader(value: CellValue): string {
  return cellText(value)?.toLowerCase().replace(/\s+/g, " ") ?? "";
}

function cellTextRaw(value: CellValue): string | null {
  if (value == null) return null;

  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (value instanceof Date) return value.toISOString();

  if (Array.isArray(value)) {
    const parts = value.map((entry) => cellTextRaw(entry)).filter((entry): entry is string => entry != null);
    return parts.length > 0 ? parts.join("") : null;
  }

  if (typeof value === "object") {
    const result = cellObjectResult(value);
    if (result !== undefined) return cellTextRaw(result);

    if ("richText" in value && Array.isArray(value.richText)) {
      const richText = value.richText
        .map((part) => {
          if (part && typeof part === "object" && "text" in part) {
            return cellTextRaw(part.text);
          }

          return null;
        })
        .filter((part): part is string => part != null)
        .join("");
      return richText === "" ? null : richText;
    }

    if ("text" in value) {
      return cellTextRaw(value.text);
    }

    const text = value.toString();
    return text === "[object Object]" ? null : text;
  }

  return null;
}

function cellObjectResult(value: object): CellValue | undefined {
  if ("result" in value) return value.result;
  return undefined;
}
