-- D-06: attachment metadata is written only by submit_lead_with_attachments().
-- The upload itself still uses the cookie-scoped anon/authenticated client, so
-- keep that Storage path but constrain it to the UUID shape generated by the route.

-- Revoke everything from anon, not only INSERT: a project that still carries
-- the legacy `grant all ... to anon, authenticated` default privileges handed
-- this table (created after 0046) full access. Staff keep SELECT for the
-- staff-read policy; nothing else writes this table except the RPC.
revoke all on table public.lead_attachments from anon;
revoke insert, update, delete on table public.lead_attachments from authenticated;

drop policy if exists "lead_capture_public_inserts_attachments"
  on public.lead_attachments;

drop policy if exists "lead_capture_public_uploads_attachments"
  on storage.objects;
create policy "lead_capture_public_uploads_attachments"
  on storage.objects for insert
  to anon, authenticated
  with check (
    bucket_id = 'lead-attachments'
    and name ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[1-9][0-9]*-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}-[A-Za-z0-9._-]{1,180}$'
  );
